kind: Secret
apiVersion: v1
metadata:
  name: springboot-hello-app
  labels:
    app: springboot-hello-app
    app.kubernetes.io/name: springboot-hello-app
    app.kubernetes.io/part-of: java-apps
    app.openshift.io/runtime: springboot
data:
  APP_TITLE: ZGVtbw==
type: Opaque