apiVersion: v1
kind: Service
metadata:
  name: springboot-hello
  labels:
    app: springboot-hello
spec:
  type: ClusterIP
  ports:
    - port: 9001
      targetPort: 9001
      protocol: TCP
      name: 9001-http
  selector:
    app: springboot-hello
